version: "3"

services:
  frontend:
    build: ./frontend/plms-reboot
    container_name: frontend-container
    ports:
      - 80:5173
    volumes:
      - ./frontend/plms-reboot/:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
      VITE_BACKEND_BASE_URL: ${BACKEND_URL}
      VITE_YEAR: 2022

  backend:
    build: ./backend/plms-reboot-ci-3
    container_name: backend-container
    ports:
      - 3000:80 
    environment:
      BASE_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      RMQ_USER: ${RMQ_USER}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_QUEUE_NAME: ${RMQ_QUEUE_NAME}
      RMQ_PORT: 5672
    volumes:
      - ./backend/plms-reboot-ci-3:/var/www/html
      - ./config/apache.conf:/etc/apache2/sites-enabled
      - ./config/php.conf:/usr/local/etc/php
    depends_on:
      - db

  db:
    image: mysql:8.0.31
    container_name: db-container
    command: --default-authentication-plugin=mysql_native_password      
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./sql-files:/sql-files

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: ${DATABASE_USER}
      PMA_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.12.11-management-alpine
    container_name: rabbitmq-container
    tty: true
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER} # Set default RabbitMQ user
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD} # Set default RabbitMQ password
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  worker:
    build: ./worker
    volumes:
      - ./worker:/app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
    environment:
      RMQ_USER: ${RMQ_USER}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      RMQ_QUEUE_NAME: ${RMQ_QUEUE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - db
      - rabbitmq
